In [3]:
import numpy as np

In [10]:
# emty arrays
empty = np.empty((3,2))
print(empty)

[[0.00000000e+000 0.00000000e+000]
 [1.12989613e-311 1.12989613e-311]
 [1.63041663e-322 1.97626258e-323]]


In [12]:
empty1 = np.empty((3))
empty1

array([1.69375949e+190, 1.75545082e-094, 7.36404175e+223])

In [17]:
print(empty1[2])
print(empty[2])

7.364041747336063e+223
[1.63e-322 1.98e-323]


In [19]:
x = np.arange(16)
print(type(x))

<class 'numpy.ndarray'>


In [17]:
# another way
even = np.arange(0,23,2)
print(even)
odd = np.arange(1,23,2)
print(odd)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[ 1  3  5  7  9 11 13 15 17 19 21]


In [19]:
# specific difference

diff = np.arange(0,23,11)
print(diff)

[ 0 11 22]


In [21]:
# for getting linear trend(like aeroplane flight or landing)

lin = np.linspace(0,10,num =7)
print(lin)
print(type(lin))

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]
<class 'numpy.ndarray'>


In [22]:
# define the datatype of array
lin = np.linspace(0,10,num =10, dtype=np.float16)
print(lin)
print(type(lin))

[ 0.     1.111  2.223  3.334  4.445  5.555  6.668  7.777  8.89  10.   ]
<class 'numpy.ndarray'>


In [27]:
# define the datatype of array
x = np.ones(2 , dtype=np.int64)
x

array([1, 1], dtype=int64)

In [32]:
x = np.arange(0,22.5,1.5 , dtype=np.float64)
x

array([ 0. ,  1.5,  3. ,  4.5,  6. ,  7.5,  9. , 10.5, 12. , 13.5, 15. ,
       16.5, 18. , 19.5, 21. ])

**Assignment 2:**

What is the difference between int32,64,float 32,64,16? why we use one and not other? 

In [34]:
# sorting an array

arr = np.array([2,1,4,5,6,4,7,8,9])
arr

array([2, 1, 4, 5, 6, 4, 7, 8, 9])

In [35]:
arr = np.sort(arr)
arr

array([1, 2, 4, 4, 5, 6, 7, 8, 9])

In [37]:
# sort on axis base

x = np.array([3,1,2])
np.argsort(x)

array([1, 2, 0], dtype=int64)

In [38]:
x = np.array([[0,3],[2,5]])
x

array([[0, 3],
       [2, 5]])

In [39]:
ind = np.argsort(x , axis = 0) # sort along first axis (down)
ind

array([[0, 0],
       [1, 1]], dtype=int64)

In [40]:
np.take_along_axis(x, ind , axis=0) # same as no.sort(x)


array([[0, 3],
       [2, 5]])

In [41]:
# concatenation 

a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
x = np.array([[1,4],[3,6]]) # 2*2
y = np.array([[5,8]]) #1*2

z =np.concatenate((x,y))
z

array([[1, 4],
       [3, 6],
       [5, 8]])

In [46]:
# concatenate 2 D arrays
z =np.concatenate((x,y), axis =0)
z

array([[1, 4],
       [3, 6],
       [5, 8]])

In [51]:
x = np.array([[1,4],[3,6]]) # 2*2
w = np.array([[5,1],[7,1]])
w

array([[5, 1],
       [7, 1]])

In [52]:
z = np.concatenate((x,w))
z

array([[1, 4],
       [3, 6],
       [5, 1],
       [7, 1]])

In [56]:
# here both dim are same(2*2), we take them on axis
z = np.concatenate((x,w), axis=1) # axis 1 mean add hirizontally,0 mean add vertically
z

array([[1, 4, 5, 1],
       [3, 6, 7, 1]])

In [62]:
print(z.ndim)
print(x.ndim)
print(w.ndim)
print(y.ndim)


2
2
2
2


In [64]:
# 3 dim array
array_example = np.array([[[0,1,2,3],
                          [4,5,6,7],],

                         [[0,1,2,3],
                          [4,5,6,7]],

                         [[0,1,2,3],
                          [4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [65]:
len(array_example)

3

In [66]:
array_example.size

24

In [67]:
array_example.dtype

dtype('int32')

In [69]:
# array 3 dim, 2 rows, 4 columns
array_example.shape 

(3, 2, 4)

In [79]:
# create an array of size 3 dim,1 row three column
a1 = np.array([[[0,1,2,3]],

                         [[4,5,6,7]],

                         [[3,2,1,3]]])
a1

array([[[0, 1, 2, 3]],

       [[4, 5, 6, 7]],

       [[3, 2, 1, 3]]])

In [80]:
a1.shape

(3, 1, 4)

In [82]:
a1.ndim # show it is 3 d array

3

In [83]:
#  reshape the a
a2 = a1.reshape(2,2,3)
a2

array([[[0, 1, 2],
        [3, 4, 5]],

       [[6, 7, 3],
        [2, 1, 3]]])

In [85]:
# 3*2*2 =12
a3 = a2.reshape(3,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]],

       [[3, 2],
        [1, 3]]])

In [86]:
# create a 1D array
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:

# add another axis on row in given array
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [88]:
print(a.shape) # 1D array
print(b.shape) # 2D array

(9,)
(1, 9)


In [91]:
# add another axis on column in given array
c = a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [92]:
c.shape

(9, 1)

# indexing and slicing

In [93]:
# 1D array
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
a[2:5]

array([3, 4, 5])

In [107]:
# 2D array
b = np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
b[1]

array([4, 5, 6, 7])

In [110]:
b[:,1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [111]:
b[b<5]

array([0, 1, 2, 3, 4])

In [113]:
b[b%2 == 0] # filter even number

array([ 0,  2,  4,  6,  8, 10])

In [114]:
# use two conditions

b[(b>2) & (b<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
# use three condition and filter the arrays
b[(b>2) & (b<11) & (b%2 == 0)]


array([ 4,  6,  8, 10])

In [117]:
# use pipe(or) operator
b[(b>2) | (b<11)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])