In [1]:
# numpy indexxing and slicing
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
a[-2]

6

In [7]:
b = np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [9]:
c =b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [10]:
c[0]

array([0, 2, 4])

In [12]:
d =c.reshape(3,2)
d

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [15]:
c[(c<5) & (c>2)]

array([4])

In [18]:
# Making an array from given data or another array
a = np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [19]:
len(a)

45

In [20]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [21]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

In [25]:
# concatenate with stacking also
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [ ]:
d = np.hstack((a,b)) # axis = 0
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
d = d.reshape(7,2)
d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])